const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const page = read("miniprogram/pages/plan/index.ts");
const template = read("miniprogram/pages/plan/index.wxml");
const goalOverview = read("miniprogram/components/goal-overview/index.wxml");
const goalOverviewStyles = read("miniprogram/components/goal-overview/index.wxss");
const metrics = read("miniprogram/components/progress-metrics/index.wxml");
const metricStyles = read("miniprogram/components/progress-metrics/index.wxss");
const trendChart = read("miniprogram/components/action-trend-chart/index.wxml");
const trendLogic = read("miniprogram/components/action-trend-chart/index.ts");
const trendStyles = read("miniprogram/components/action-trend-chart/index.wxss");
const coachInsight = read("miniprogram/components/coach-insight/index.wxml");
const coachInsightStyles = read("miniprogram/components/coach-insight/index.wxss");
const coachPage = read("miniprogram/pages/ai-coach/index.ts");
const coachService = read("miniprogram/services/progressCoach.ts");

assert.match(template, /还没有目标/);
assert.match(template, /先创建一个想推进的方向/);
assert.match(goalOverview, /当前目标/);
assert.match(goalOverview, /goal-stage/);
assert.doesNotMatch(goalOverview, /progress-mountain-path-v2\.jpg|goal-overview__image|goal-overview__wash/, "当前目标卡不应重复叠加独立山水背景");
assert.doesNotMatch(goalOverview, /goal-overview__gold-rail/, "连续宣纸版式不应保留目标卡金色侧栏");
assert.match(goalOverviewStyles, /background:\s*transparent/);
assert.match(goalOverview, /成长期/);
assert.match(goalOverview, /稳定期/);
assert.match(goalOverview, /canvas-id="goalStageCanvas"/, "目标阶段路径应保留持续向上的曲线表达");
assert.match(read("miniprogram/components/goal-overview/index.ts"), /function cubicCoordinate/);
assert.match(read("miniprogram/components/goal-overview/index.ts"), /\[0, 1 \/ 3, 2 \/ 3, 1\][\s\S]*pointAt\(progress\)/, "四个阶段节点应由同一条贝塞尔曲线计算");
assert.match(read("miniprogram/components/goal-overview/index.ts"), /currentProgress[\s\S]*pointAt\(currentProgress\)/, "真实进度节点应复用同一曲线坐标函数");
assert.match(page, /function getProgressHeaderLayout\(\)[\s\S]{0,320}headerHeight: layout\.headerHeight \+ 18/, "进度品牌副标题需要独立的垂直空间");
assert.match(template, /class="progress-subtitle">持续行动 · 长期成长<\/text>/, "进度品牌字下方应显示副标题");
assert.match(template, /overviewStats/);
assert.match(template, /<goal-overview/);
assert.match(template, /<progress-metrics/);
assert.match(metrics, /当前统计范围数据概览/);
assert.match(metrics, /查看历史记录/);
assert.match(metricStyles, /border-radius:\s*0/);
assert.match(metricStyles, /background:\s*transparent/);
assert.match(template, /bind:history="openHistoryReview"/);
assert.doesNotMatch(template, /class="growth-stats surface-card"/, "目标累计不应继续使用独立卡片");
assert.doesNotMatch(template, /goal-hero__landscape|goal-hero__veil/, "目标卡不应与顶部重复叠加山水背景");
assert.match(template, /\{\{canSwitchGoal \? '切换目标' : '查看目标'\}\}/);
assert.match(page, /持续目标 · \$\{year\}年\$\{month\}月\$\{day\}日开始/);
assert.doesNotMatch(template, /goal\.description/, "顶部目标卡只保留目标与起始日期");
assert.doesNotMatch(template, /累计行动完成率|goal-progress|goalProgressPercent/);
assert.match(template, /class="growth-record-entry surface-card"/);
assert.match(template, /bindtap="openGrowthRecords"/);
assert.match(page, /pages\/growth-records\/index\?from=progress&goalId=/);
assert.match(template, /class="recent-completion-card surface-card"/, "进度页底部应提供最近完成列表卡片");
assert.match(template, /最近完成/);
assert.match(template, /近 7 天完成 \{\{recentCompletedCount\}\} 项/);
assert.match(template, /wx:for="\{\{recentCompletedTasks\}\}" wx:key="id"/, "最近完成记录需要使用稳定唯一 key 持续渲染");
assert.match(template, /bindtap="openRecentTask"/, "完成记录必须可以进入行动详情");
assert.match(template, /bindtap="openRecentHistory"/, "最近完成卡必须提供完整历史入口");
assert.match(page, /completed\.slice\(0, 3\)/, "进度页最多展示 3 条最近完成记录");
assert.match(page, /formatDate\(addDays\(toDate\(today\), -6\)\)/, "最近完成必须使用近 7 个自然日口径");
assert.match(template, /<completed-record-editor/, "完成记录点击后必须打开完成记录专用编辑器");
assert.doesNotMatch(page, /openRecentTask[\s\S]{0,700}pages\/action-edit/, "完成记录不得进入任务配置页");
assert.match(page, /efficiencyLabel: savedMinutes > 0 \? `提前 \$\{savedMinutes\} 分钟完成`/);
assert.match(template, /wx:if="\{\{hasTrendData\}\}" insight="\{\{coachInsight\}\}"/);
assert.match(coachInsight, /教练观察/);
assert.match(coachInsight, /完整分析/);
assert.match(coachInsight, /下一步建议/);
assert.match(coachInsight, /预计用时约 1 分钟/);
assert.doesNotMatch(coachInsight, /theme="circle"|coach-score/, "教练观察不得继续使用圆环稳定性图");
assert.match(coachInsight, /progress-goal-mountains-v1\.jpg/, "山水签批方案必须复用正式群峰背景资源");
assert.match(coachInsight, /today-action-seal-v1\.png/, "教练标题必须使用正式红色印记资源");
assert.match(coachInsight, /today-action-brush-gold-v1\.png/, "教练观察与建议应由真实金色笔触资源串联");
assert.match(coachInsight, /insight\.conclusion/);
assert.match(coachInsight, /insight\.evidence/);
assert.match(coachInsight, /insight\.advice/);
assert.match(coachInsightStyles, /\.coach-conclusion\s*\{[^}]*font-family:\s*var\(--font-family-brand\)[^}]*font-size:\s*var\(--font-card-title\)[^}]*font-weight:\s*500/, "教练结论应使用卡片标题层级的东方文字");
assert.doesNotMatch(coachInsightStyles, /\.coach-action\s*\{/, "山水签批方案不得保留卡片套卡片的建议行动容器");
assert.match(template, /scope-label="\{\{coachScopeLabel\}\}"/, "教练观察应显示真实周月年范围");
assert.match(template, /bind:action="arrangeCoachAction"/);
assert.match(page, /openTodayActionEditor\(\{ mode: "create", goalId, date: tomorrow \}\)/, "建议行动必须通过今日页统一半屏进入明日任务安排流程");
assert.match(page, /summary\.summaryText/);
assert.match(trendChart, /完成行动（项）/);
assert.match(trendChart, /summary\.activityLabel/);
assert.match(trendChart, /today-action-seal-v1\.png/);
assert.match(trendStyles, /background:\s*transparent/);
assert.match(trendStyles, /\.chart-shell\s*\{[^}]*height:\s*340rpx/, "趋势图应压缩高度，为底部横轴标签留出完整可见空间");
assert.doesNotMatch(trendStyles, /\.chart-shell\s*\{[^}]*height:\s*430rpx/, "趋势图不应继续被底部导航遮挡横轴标签");
assert.match(metrics, /item\.label/);
assert.match(page, /label: "最高投入"/);
assert.match(page, /label: "平均投入"/);
assert.match(page, /label: "连续投入天数"/);
assert.doesNotMatch(trendChart, /下一里程碑/);
assert.match(trendChart, /<canvas canvas-id="trendCanvas"/);
assert.match(trendLogic, /bezierCurveTo/);
assert.match(trendLogic, /isCrowded[\s\S]*nearBottom[\s\S]*labelX[\s\S]*labelY/, "双序列标签必须根据点位拥挤程度进行避让");
assert.match(trendLogic, /nearTop[\s\S]*point\.y \+ 22/, "触顶的首日分钟标签应下移，避免被绿色数据点遮挡");
assert.match(page, /weekdayLabel\(bestStart\)\}～\$\{weekdayLabel\(bestEnd\)/, "连续投入日期应使用清晰的波浪连接符");
assert.match(page, /isFuture:\s*date\s*>\s*today/, "周趋势必须明确标记今天之后的未来日期");
assert.match(page, /occurredBars\s*=\s*bars\.filter\(\(item\)\s*=>\s*!item\.isFuture\)/, "趋势刻度不得由未来日期参与计算");
assert.match(trendLogic, /visibleMinutePoints\s*=\s*minutePoints\.filter\(\(_,\s*index\)\s*=>\s*!bars\[index\]\.isFuture\)/, "投入折线必须在未来日期前终止");
assert.match(trendLogic, /activeBars\s*=\s*bars\.filter\(\(bar\)\s*=>\s*!bar\.isFuture\s*&&\s*bar\.minutes\s*>\s*0\)/, "平均投入不得包含未来日期");
assert.match(trendChart, /item\.isFuture\s*\?\s*'is-future'/, "未来日期标签必须有独立弱化状态");
assert.doesNotMatch(template, /trendLine/);
assert.match(trendChart, /添加今日行动/);
assert.match(trendChart, /去今日页开始行动/);
assert(template.indexOf("<action-trend-chart") < template.indexOf("<coach-insight"), "行动趋势必须排在教练观察之前");
assert.match(template, /progress-pine-ridge-v1\.jpg/, "进度页顶部应使用用户提供的松林背景");
assert.match(template, /progress-goal-mountains-v1\.jpg/, "目标进程区应使用用户提供的群峰背景");
assert(fs.existsSync(path.join(root, "miniprogram/assets/progress-pine-ridge-v1.jpg")));
assert(fs.existsSync(path.join(root, "miniprogram/assets/progress-goal-mountains-v1.jpg")));
assert.match(template, /progress-brand-lockup-v1\.png/, "进度页标题应使用独立绘制的品牌字图");
assert.match(template, /progress-mountain-path-v2\.jpg/, "进度页空状态应保留原有山水品牌资源");
assert.doesNotMatch(template, /ai-coach-shanshui-v1\.jpg/, "紧凑 AI 入口不应继续使用强背景图");

assert.doesNotMatch(page, /analyzeProgress\s*\(/, "进入进度页不得自动生成 AI 报告");
assert.doesNotMatch(page, /prepareProgressCoach\s*\(/, "进入进度页不得发起 AI 上下文网络请求");
assert.doesNotMatch(coachPage, /prepareProgressCoach\s*\(/, "打开 AI 面板不得自动发起上下文网络请求");
assert.match(coachService, /askProgressCoach[\s\S]*await verifyCoachRuntime\(\);[\s\S]*await syncManualData\(\);/, "只能在用户发送问题时同步可信数据并调用 AI");
assert.doesNotMatch(
  coachService.slice(coachService.indexOf("export async function askProgressCoach"), coachService.indexOf("export async function getCoachConversation")),
  /prepareProgressCoach\(/,
  "普通问答不应依赖旧快照或进行中目标",
);
assert.match(page, /task\.activityDate \|\| task\.currentDate/, "趋势必须使用真实行动业务日期");
assert.match(page, /task\.status === "rescheduled"[\s\S]*task\.statusBeforeReschedule === "partially_completed"[\s\S]*\(task\.actualMinutes \|\| 0\) > 0/, "顺延前真实投入必须保留");
assert.match(page, /getTaskHistoryByGoal/, "趋势必须使用包含顺延历史的分析专用查询");
assert.match(page, /on\("manual:sync"/);
assert.match(page, /off\("manual:sync"/);
assert.doesNotMatch(page, /超过了 \$\{percentile\}% 的用户/, "不得伪造用户分位比较");
assert.match(page, /const insufficient = checkinDays < 1/, "年度热力图只能在完全无记录时进入空状态");
assert.match(coachService, /!task\.deletedAt/, "AI 上下文必须排除软删除行动");
assert.match(page, /function buildWeekBuckets/);
assert.match(page, /function buildMonthBuckets/);
assert.match(page, /function trendPeriodLabel/);
assert.match(page, /pages\/today-data\/index/, "查看历史记录必须进入当前目标的每日记录闭环");
assert.doesNotMatch(page, /暂无历史复盘/, "当前目标历史入口不应错误依赖已归档目标");

console.log("进度页三态、真实统计与 AI 按需调用契约测试通过");
