const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const component = fs.readFileSync(path.join(root, "components/coach-chat/index.ts"), "utf8");
const template = fs.readFileSync(path.join(root, "components/coach-chat/index.wxml"), "utf8");
const styles = fs.readFileSync(path.join(root, "components/coach-chat/index.wxss"), "utf8");
const service = fs.readFileSync(path.join(root, "services/progressCoach.ts"), "utf8");
const daily = fs.readFileSync(path.join(root, "pages/daily-coach/index.wxml"), "utf8");
const overall = fs.readFileSync(path.join(root, "pages/ai-coach/index.wxml"), "utf8");
const dailyLogic = fs.readFileSync(path.join(root, "pages/daily-coach/index.ts"), "utf8");
const overallLogic = fs.readFileSync(path.join(root, "pages/ai-coach/index.ts"), "utf8");
const appConfig = JSON.parse(fs.readFileSync(path.join(root, "app.json"), "utf8"));

assert.match(component, /slice\(0, 1000\)/);
assert.match(template, /<textarea[^>]*maxlength="1000"[^>]*auto-height/s);
assert.match(template, /bindconfirm="sendQuestion"/);
assert.match(template, /coach-chat__send/);
assert.doesNotMatch(template, /t-chat-sender|开始对话|emoji|表情|name="add"|name="plus"/, "输入区不得恢复重型聊天输入器、开始按钮、表情或加号");
assert.doesNotMatch(template, /coach-chat__composer-brand/, "输入框左侧不得保留品牌图标");
assert.match(template, /name="chevron-up"/, "发送按钮应使用明确的向上箭头指引");
assert.doesNotMatch(template, /send-filled/, "发送按钮不得继续使用填充图标");
assert.match(template, /adjust-position="\{\{true\}\}"/);
assert.doesNotMatch(template, /coach-chat__input-note/);
assert.match(template, /coach-chat__answer">\{\{item\.content\}\}<\/view>/);
assert.match(template, /userAvatarUrl/);
assert.match(template, /item\.presentation\.metrics/);
assert.match(template, /item\.presentation\.priorities/);
assert.match(template, /item\.presentation\.timeline/);
assert.match(template, /item\.presentation\.comparison/);
assert.match(template, /item\.presentation\.trend/);
assert.match(template, /item\.presentation\.team/);
assert.match(template, /item\.presentation\.action/);
assert.match(template, /<t-avatar/);
assert.match(template, /<t-progress/);
assert.match(template, /<t-tag/);
assert.match(template, /<t-chat-thinking/);
assert.match(template, /coach-mark\.svg/);
assert.match(template, /coach-chat__message-time/);
assert.match(template, /coach-chat__feedback-button/);
assert.doesNotMatch(template, /开始对话|openComposer|openQuickGuide|openActionGuide/);
assert.match(template, /coach-chat__structure-label[^>]*>[\s\S]*结论/);
assert.match(template, /item\.presentation\.kind === 'direct'[\s\S]*\{\{item\.content\}\}/);
assert.doesNotMatch(component, /sendFromSender|senderPresets|senderTextareaProps|openQuickGuide|openActionGuide|openComposer/);
assert.match(component, /formatCoachTime/);
assert.match(component, /rateAnswer/);
assert.match(styles, /\.coach-chat__answer[^}]*white-space:\s*pre-wrap/s);
assert.match(styles, /overflow-wrap:\s*anywhere/);
assert.doesNotMatch(styles, /@import\s+["']\.\.\/\.\.\/styles\/theme\.wxss/, "组件不得导入含 page 和属性选择器的全局主题样式");
assert.match(styles, /coach-chat__composer/);
assert.match(styles, /\.coach-chat__composer\s*\{[^}]*position:\s*fixed[^}]*bottom:\s*calc\(16rpx \+ env\(safe-area-inset-bottom\)\)/s, "输入区必须吸附在安全区上方");
assert.match(styles, /\.coach-chat__anchor\s*\{[^}]*160rpx/s, "页面末尾必须给吸底输入区预留遮挡空间");
assert.match(styles, /\.coach-chat__send\s*\{[^}]*border:\s*none[^}]*background:\s*var\(--color-primary/s, "发送按钮应为圆形墨绿色主操作");
assert.match(styles, /\.coach-chat__send-accent\s*\{[^}]*background:\s*#d5aa58/s, "发送按钮保留克制的金色细节");
assert.match(template, /教练正在等你/);
assert.match(template, /随时聊聊你的困惑与下一步/);
assert.match(component, /scrollToLatest\(\)/);
assert.match(component, /wx\.pageScrollTo/);
assert.match(component, /selectAll\("\.coach-chat__message"\)/);
assert.match(component, /select\("\.coach-chat__composer"\)/);
assert.doesNotMatch(styles, /(^|[,{]\s*)(?:button|view|text|image|textarea|input|scroll-view)(?:\s|:|\{|,)/m, "组件 WXSS 不得使用标签选择器");
assert.doesNotMatch(styles, /\.[A-Za-z0-9_-]+\[[^\]]+\]/, "组件 WXSS 不得使用属性选择器");
assert.doesNotMatch(template, /rich-text|markdown|item\.(?:summary|advice|insights)|展开完整回复/);
assert.match(service, /action:\s*"getCoachConversation"/);
assert.match(service, /limit:\s*Math\.max\(1, Math\.min\(50/);
assert.match(daily, /<coach-chat/);
assert.match(overall, /<coach-chat/);
assert.match(daily, /id="coach-chat"/);
assert.match(overall, /id="coach-chat"/);
assert.match(dailyLogic, /scrollChatToLatest\(\)/);
assert.match(overallLogic, /scrollChatToLatest\(\)/);
assert.doesNotMatch(dailyLogic, /scrollIntoView/);
assert.doesNotMatch(overallLogic, /scrollIntoView/);
assert.equal(appConfig.usingComponents["coach-chat"], "/components/coach-chat/index");

console.log("coach chat contract tests passed");
