const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const page = fs.readFileSync(path.join(root, "pages/daily-coach/index.ts"), "utf8");
const template = fs.readFileSync(path.join(root, "pages/daily-coach/index.wxml"), "utf8");
const config = JSON.parse(fs.readFileSync(path.join(root, "pages/daily-coach/index.json"), "utf8"));
const chatTemplate = fs.readFileSync(path.join(root, "components/coach-chat/index.wxml"), "utf8");
const chatStyles = fs.readFileSync(path.join(root, "components/coach-chat/index.wxss"), "utf8");
const service = fs.readFileSync(path.join(root, "services/dailyCoach.ts"), "utf8");

assert.match(template, /今日结论/);
assert.match(template, /教练判断/);
assert.doesNotMatch(template, /下一步建议|next-step|runPrimaryAction|runSecondaryAction/);
assert.match(template, /title="继续问教练"/);
assert.match(template, /今日行动完成率/);
assert.doesNotMatch(template, /jinbuju-ai-robot|coach-robot|帮我分析一下今天的完成情况<\/view>/, "页面不应伪造聊天或继续使用卡通机器人");
assert.match(page, /getDailyCoachAnalysis/);
assert.match(page, /askProgressCoach\("day"/);
assert.match(page, /executeCoachProposal/);
assert.match(page, /executingProposalId:\s*"",\s*chatError:\s*"",\s*failedQuestion:\s*""/, "确认执行成功后必须清除残留错误提示");
assert.doesNotMatch(page, /updateActionRecord|action-record-editor|recordEditorVisible/);
assert.doesNotMatch(page, /getCoachConversation|loadConversation/, "每日页重新进入时不得恢复历史会话");
assert.match(page, /messages:\s*\[\],\s*conversationId:\s*""/, "每次进入每日教练页都应开始新会话");
assert.match(page, /this\.data\.conversationId \|\| undefined/, "当前页面内应保留多轮上下文");
assert.match(page, /slice\(-50\)/, "当前页面最多展示最近 50 条消息");
assert.match(page, /scope=week/, "最近一周必须进入真实周分析能力");
assert.match(page, /getMenuButtonBoundingClientRect/, "自定义导航必须避让微信右上角胶囊");
assert.match(template, /padding-right: \{\{menuRightInset\}\}px/, "导航未使用真实胶囊右侧占位");
assert.match(template, /<coach-chat/);
assert.match(chatTemplate, /maxlength="1000"/);
assert.match(chatStyles, /white-space:\s*pre-wrap/, "无模板回复必须保留正文换行和空格");
assert.doesNotMatch(chatTemplate, /展开完整回复|item\.(?:summary|insights|advice)/, "共享聊天不得恢复旧版摘要字段和折叠交互");
assert.doesNotMatch(template, /明日建议|subscribeAiCoachAdvice|notification-optin/);
assert.doesNotMatch(template, /<button class="(?:nav-back|records-button|send-button|quick-question)/, "易被基础库拉伸的导航和快捷控件不应使用原生 button");
assert.match(service, /status !== "skipped"/, "每日教练完成率应与今日页排除“今天不做”的口径一致");
assert.equal(config.usingComponents["action-record-editor"], undefined);
assert.equal(config.usingComponents["t-icon"], "tdesign-miniprogram/icon/icon");
  assert.equal(config.usingComponents["coach-chat"], undefined, "分包页面应继承主包全局聊天组件，避免按需打包漏载");

console.log("daily coach workspace tests passed");
