const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(root, "pages/ai-coach/index.ts"), "utf8");
const template = fs.readFileSync(path.join(root, "pages/ai-coach/index.wxml"), "utf8");
const styles = fs.readFileSync(path.join(root, "pages/ai-coach/index.wxss"), "utf8");
const config = JSON.parse(fs.readFileSync(path.join(root, "pages/ai-coach/index.json"), "utf8"));
const chatTemplate = fs.readFileSync(path.join(root, "components/coach-chat/index.wxml"), "utf8");

assert.doesNotMatch(styles, /daily-coach\/index\.wxss/, "进度 AI 页面不能再依赖每日教练页面样式");
assert.doesNotMatch(template, /jinbuju-ai-robot|coach-robot/, "成长洞察不应继续展示卡通机器人");
assert.match(source, /getMenuButtonBoundingClientRect/, "成长洞察自定义导航必须避让系统胶囊");
assert.match(template, /AI 成长教练/);
assert.match(template, /class="scope-switch"/);
assert.match(template, /data-scope="day"[\s\S]*data-scope="week"[\s\S]*data-scope="month"[\s\S]*data-scope="overall"/);
assert.match(template, /ai-coach-shanshui-v2\.jpg/);
assert.match(source, /label:\s*"完成行动"/);
assert.match(template, /class="metric-grid"/);
assert.match(template, /metricCards/);
assert.match(template, /rhythmPoints/);
assert.match(template, /reviewItems/);
assert.match(template, /goalItems/);
assert.match(template, /本周建议[\s\S]*本月建议[\s\S]*长期建议/, "三个范围必须拥有各自的建议语义");
assert.match(source, /本周行动回顾[\s\S]*本月行动回顾[\s\S]*目标全景/);
assert.match(template, /bindtap="sendGuidedQuestion"/, "范围快捷问题必须进入现有 AI 问答链路");
assert.match(template, /bindtap="openReviewItem"/, "周月行动回顾必须可进入真实行动编辑");
assert.doesNotMatch(template, /今日行动/, "周月与长期页面不得复制今日行动模块");
assert.doesNotMatch(template, /quick-questions=/, "快捷问题已归入范围建议卡，不应在聊天组件重复展示");
assert.doesNotMatch(template, /microphone|voice|waveform|麦克风|语音/);
assert.match(source, /getTaskHistoryByGoal/, "范围统计必须保留顺延前已经发生的真实投入");
assert.match(source, /getArchivedGoals/, "长期洞察必须纳入历史目标沉淀");
assert.match(source, /new Date\(date\.getFullYear\(\), date\.getMonth\(\), 1\)/, "本月范围必须按自然月起点统计");
assert.match(source, /date\.getDay\(\) \+ 6\) % 7/, "本周范围必须按自然周起点统计");
assert.match(source, /buildRhythm/);
assert.match(source, /goalInsightItems/);
assert.match(source, /\["为什么这样建议", "本周总结", "找出本周问题"\]/);
assert.match(source, /\["查看进步总结", "本月总结", "找出高效习惯"\]/);
assert.match(source, /\["当前方向对吗", "拆解长期路径", "回顾成长变化"\]/);
assert.match(chatTemplate, /教练正在等你[\s\S]*随时聊聊你的困惑与下一步/);
assert.doesNotMatch(chatTemplate, /开始对话/, "共享教练组件不应增加冗余的开始按钮");
assert.match(template, /继续问教练/);
assert.match(template, /<coach-chat/);
assert.doesNotMatch(source, /getCoachConversation|loadConversation/, "成长教练重新进入时不得恢复历史会话");
assert.match(source, /messages:\s*\[\],\s*conversationId:\s*""/, "每次进入成长教练页都应开始新会话");
assert.match(source, /selectCoachScope/);
assert.match(source, /this\.data\.conversationId \|\| undefined/, "当前页面内应保留多轮上下文");
assert.match(chatTemplate, /\{\{item\.content\}\}/, "旧云函数或无模板回复必须保留正文降级展示");
assert.doesNotMatch(chatTemplate, /展开完整回复|reply-full|assistant-summary/);
assert.equal(config.navigationBarTitleText, "AI 成长教练");
  assert.equal(config.usingComponents["coach-chat"], undefined, "分包页面应继承主包全局聊天组件，避免按需打包漏载");

console.log("progress coach workspace tests passed");
